prefix = "."
stop-words = "stopwords.txt"

dataset = "text_data"
corpus = "line.toml"
index = "idx"
type = "line-corpus"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "subtitle-queries.txt"
query-id-start = 1

